import { SubtitleCue, SubtitleWord, Scene } from './types';

export function generateSubtitleCues(scenes: Scene[]): SubtitleCue[] {
  const cues: SubtitleCue[] = [];
  let currentSec = 0;

  scenes.forEach((scene, sceneIndex) => {
    const text = scene.narrationText.trim();
    if (!text) {
      currentSec += scene.durationSec;
      return;
    }

    const words = text.split(/\s+/).filter(Boolean);
    const sceneStart = currentSec;
    const sceneEnd = currentSec + scene.durationSec;
    const wordDuration = scene.durationSec / Math.max(words.length, 1);

    const subWords: SubtitleWord[] = words.map((w, wIndex) => ({
      word: w,
      startSec: Number((sceneStart + (wIndex * wordDuration)).toFixed(2)),
      endSec: Number((sceneStart + ((wIndex + 1) * wordDuration)).toFixed(2)),
    }));

    // Group into 4-6 word chunks for readable captions
    const chunkSize = 5;
    for (let i = 0; i < words.length; i += chunkSize) {
      const chunkWords = subWords.slice(i, i + chunkSize);
      const chunkText = words.slice(i, i + chunkSize).join(' ');
      const chunkStart = chunkWords[0]?.startSec ?? sceneStart;
      const chunkEnd = chunkWords[chunkWords.length - 1]?.endSec ?? sceneEnd;

      cues.push({
        id: `cue-${sceneIndex}-${i}`,
        startSec: chunkStart,
        endSec: chunkEnd,
        text: chunkText,
        words: chunkWords,
      });
    }

    currentSec += scene.durationSec;
  });

  return cues;
}

function formatSrtTimestamp(seconds: number): string {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);

  return `${String(hrs).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')},${String(ms).padStart(3, '0')}`;
}

export function exportToSrt(cues: SubtitleCue[]): string {
  return cues.map((cue, index) => {
    return `${index + 1}\n${formatSrtTimestamp(cue.startSec)} --> ${formatSrtTimestamp(cue.endSec)}\n${cue.text}\n`;
  }).join('\n');
}

export function exportToVtt(cues: SubtitleCue[]): string {
  const header = 'WEBVTT - Generated by NahaLabs Video Engine\n\n';
  const body = cues.map((cue, index) => {
    return `${index + 1}\n${formatSrtTimestamp(cue.startSec).replace(',', '.')} --> ${formatSrtTimestamp(cue.endSec).replace(',', '.')}\n${cue.text}\n`;
  }).join('\n');
  return header + body;
}

export function getActiveCueAtTime(cues: SubtitleCue[], currentSeconds: number): SubtitleCue | null {
  return cues.find(c => currentSeconds >= c.startSec && currentSeconds <= c.endSec) || null;
}
